# Fast Fourier Transform

examples

In [1]:
import numpy as np
from fractions import Fraction
from functools import reduce, lru_cache, partial

from scipy import linalg as la
import scipy.optimize as opt
from scipy import special, interpolate, integrate
import matplotlib.pyplot as plt
from numpy.polynomial import Polynomial
np.set_printoptions(suppress=True, precision=6)

def sign(x):
    s = np.sign(x)
    return s if s else 1

In [ ]:
def generate_f(n):
    w = np.exp(complex(0, - 2 * np.pi / n))
    return np.vander(w ** np.arange(n), increasing=True)


def generate_f_inv(n):
    w = np.exp(complex(0, - 2 * np.pi / n))
    return np.vander(w ** (-np.arange(n)), increasing=True) / n


n = 4
F = generate_f(n)
F_inv = generate_f_inv(n)
F @ F_inv

array([[ 1.+0.j, -0.+0.j,  0.+0.j,  0.+0.j],
       [-0.-0.j,  1.+0.j, -0.+0.j,  0.+0.j],
       [ 0.-0.j, -0.-0.j,  1.+0.j, -0.+0.j],
       [ 0.-0.j,  0.-0.j, -0.-0.j,  1.+0.j]])

In [16]:
# 12.1
x = np.array([4, 0, 3, 6, 2, 9, 6, 5])
print(x.sum())
generate_f(8) @ x

35


array([35.      +0.j      , -5.071068+8.656854j, -3.      +2.j      ,
        9.071068+2.656854j, -5.      +0.j      ,  9.071068-2.656854j,
       -3.      -2.j      , -5.071068-8.656854j])

In [15]:
x = np.ones(8)
x[1::2] *= -1
print(x.sum())
generate_f(8) @ x

0.0


array([ 0.+0.j, -0.+0.j, -0.-0.j, -0.-0.j,  8.+0.j, -0.+0.j, -0.+0.j,
       -0.+0.j])